export const refs = {
  paginationBox: document.getElementById('tui-pagination'),
  categoriesContainer: document.querySelector('.js-categories-container'),
  categoriesList: document.querySelector('.js-categories-list'),
  exercise: document.querySelector('.js-exercise'),
  exerciseDecor: document.querySelector('.js-exercise-decor'),
  categoryError: document.querySelector('.js-categories-error'),
  categorySceletonLoader: document.querySelector('.js-sceleton-loader'),
  search: document.querySelector('.js-search'),
  exerciseRefresh: document.querySelector('.js-refresh'),
  searchIcon: document.querySelector('.menu-search-icon'),
  closeIcon: document.querySelector('.menu-close-icon'),
  searchBtn: document.querySelector('.menu-search-btn'),
  searchInput: document.querySelector('.menu-search-input'),
};
